2016-11-24 19:28:08,507 - __main__ - INFO - Start...
2016-11-24 19:28:54,664 - __main__ - INFO - Start...
2016-11-24 19:28:58,429 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:28:58,697 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:30:45,814 - __main__ - INFO - Start...
2016-11-24 19:30:52,188 - __main__ - ERROR - Traceback (most recent call last):
  File "server.py", line 58, in wrapper
    f(self, *args, **kwargs)
TypeError: get() takes exactly 2 arguments (1 given)

2016-11-24 19:30:52,188 - __main__ - INFO - {"msg": "\u672a\u77e5\u9519\u8bef: get() takes exactly 2 arguments (1 given)", "code": 1}
2016-11-24 19:30:52,399 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:31:06,966 - __main__ - INFO - Start...
2016-11-24 19:31:11,796 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:31:14,340 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:31:16,466 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:31:19,974 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:31:32,537 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:31:40,638 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:38:02,618 - __main__ - INFO - Start...
2016-11-24 19:38:05,000 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:38:12,951 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:38:19,771 - __main__ - INFO - Start...
2016-11-24 19:38:22,597 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:38:46,487 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:43:48,257 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:44:08,632 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:45:51,849 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:46:28,445 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:46:44,916 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:48:19,772 - __main__ - INFO - hello
2016-11-24 19:55:14,833 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:04,779 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:05,211 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:08,160 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:10,367 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:10,521 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:35,655 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:36,111 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:37,518 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:56:37,909 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:58:07,070 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:58:07,356 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:58:11,369 - __main__ - ERROR - Traceback (most recent call last):
  File "server.py", line 58, in wrapper
    f(self, *args, **kwargs)
  File "server.py", line 118, in get
    self.render("kline.html")
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 699, in render
    html = self.render_string(template_name, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 806, in render_string
    return t.generate(**namespace)
  File "/Library/Python/2.7/site-packages/tornado/template.py", line 345, in generate
    return execute()
  File "kline_html.generated.py", line 5, in _tt_execute
    _tt_tmp = static_url('kline.js')  # kline.html:12
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1308, in static_url
    self.require_setting("static_path", "static_url")
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1326, in require_setting
    "application to use %s" % (name, feature))
Exception: You must define the 'static_path' setting in your application to use static_url

2016-11-24 19:58:11,370 - __main__ - INFO - {"msg": "\u672a\u77e5\u9519\u8bef: You must define the 'static_path' setting in your application to use static_url", "code": 1}
2016-11-24 19:58:11,531 - __main__ - INFO - {"msg": "\u9519\u8bef\u7684\u8bf7\u6c42\u8def\u5f84", "code": 1}
2016-11-24 19:58:19,775 - __main__ - INFO - hello
2016-11-24 19:59:32,486 - __main__ - INFO - Start...
2016-11-24 20:09:32,488 - __main__ - INFO - hello
2016-11-24 20:19:32,489 - __main__ - INFO - hello
2016-11-24 20:29:32,490 - __main__ - INFO - hello
2016-11-24 20:39:32,492 - __main__ - INFO - hello
2016-11-24 20:49:32,493 - __main__ - INFO - hello
2016-11-24 20:59:32,494 - __main__ - INFO - hello
2016-11-24 21:09:32,496 - __main__ - INFO - hello
2016-11-24 21:19:32,498 - __main__ - INFO - hello
2016-11-24 21:29:32,501 - __main__ - INFO - hello
2016-11-24 21:35:50,831 - __main__ - INFO - Start...
2016-11-24 21:45:50,834 - __main__ - INFO - hello
2016-11-24 21:56:33,964 - __main__ - INFO - Start...
2016-11-24 22:04:56,664 - __main__ - INFO - Start...
2016-11-24 22:14:56,669 - __main__ - INFO - hello
2016-11-24 22:16:02,608 - __main__ - INFO - Start...
2016-11-24 22:16:44,076 - __main__ - INFO - Start...
2016-11-24 22:23:00,070 - __main__ - INFO - Start...
2016-11-24 22:30:16,752 - __main__ - INFO - Start...
2016-11-24 22:44:38,783 - __main__ - INFO - Start...
2016-11-24 22:54:38,787 - __main__ - INFO - hello
2016-11-24 22:55:36,503 - __main__ - ERROR - Traceback (most recent call last):
  File "server.py", line 102, in wrapper
    f(self, *args, **kwargs)
  File "server.py", line 168, in post
    data = get_daily_data(code)
  File "server.py", line 54, in get_daily_data
    data['dates'] = ohlc_df.index_col.values.tolist()
  File "/Library/Python/2.7/site-packages/pandas/core/generic.py", line 2246, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'index_col'

2016-11-24 22:55:36,504 - __main__ - INFO - {"msg": "\u672a\u77e5\u9519\u8bef: 'DataFrame' object has no attribute 'index_col'", "code": 1}
2016-11-24 22:56:00,477 - __main__ - INFO - Start...
2016-11-24 23:04:18,695 - __main__ - INFO - Start...
2016-11-24 23:06:22,355 - __main__ - INFO - Start...
